### ISSUE TITLE
Schematic or close picture of connection

### ISSUE THREAD

**Issue by SCiunczyk** [pootle/tripipy#10]
Hi,

yes I know you can call me lazy bastard ;-), but I'll be more than happy if you can share the connection scheme you made on "Adafruit Perma-Proto HAT for Pi". Or just close photo of wiring will by nice. 

I just want to minimize probability to receive smoke signals from TMC5130A-BOB's or RPi itself.

best regards
Slawek

**Comment by pootle** [comment]
Here's some piccies, the wiring is pretty straightforward as apart from the control signals is just power hookup really.

![20200623_090354](https://user-images.githubusercontent.com/919663/85377525-219a3280-b531-11ea-9fe2-8478dc1aab47.jpg)
![20200623_090408](https://user-images.githubusercontent.com/919663/85377537-24952300-b531-11ea-9a14-00948adc1f96.jpg)
![20200623_090419](https://user-images.githubusercontent.com/919663/85377546-2828aa00-b531-11ea-9d76-fde465bcf39f.jpg)
![20200623_090442](https://user-images.githubusercontent.com/919663/85377555-2b239a80-b531-11ea-8d16-b53e500eb664.jpg)

**Comment by SCiunczyk** [comment]
Many thanks for your help.
